docs_dir: docs/book
site_dir: docs/html
nav:
    - Home: index.md
    - Introduction: intro.md
    - "Integration testing with PHPUnit": phpunit.md
    - Assertions: assertions.md
site_name: laminas-test
site_description: "Tools to facilitate integration testing of laminas-mvc applications"
repo_url: 'https://github.com/laminas/laminas-test'
extra:
    project: MVC
